name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    # BOTUN YAZMA İZNİ OLMASI İÇİN BU KISIM ŞART:
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: umitarat-dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated Snake Animation"
          branch: output
          create_branch: true
          file_pattern: 'dist/*.svg'
          # DEĞİŞİKLİK YOKSA HATA VERME:
          skip_dirty_check: false 
          skip_fetch: false